version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      PROJECT_ENVIRONMENT: "DEVELOPMENT"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8001:8001"
